export enum ActionTypes {
  SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES',
  SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS',
  SEARCH_REPOSITORIES_ERROR = 'SEARCH_REPOSITORIES_ERROR',
  ADD_FAVORITE_REPOSITORY = 'ADD_FAVORITE_REPOSITORY',
  DELETE_FAVORITE_REPOSITORY = 'DELETE_FAVORITE_REPOSITORY',
  REPOSITORIES_FILTER = 'REPOSITORIES_FILTER'
}
